blank_issues_enabled: true
contact_links:
  - name: Have an idea for Moonwalk?
    url: https://github.com/OAI/sig-moonwalk/discussions
    about: Please open or join a discussion instead of an issue!
  - name: Want to chat about Moonwalk?
    url: https://communityinviter.com/apps/open-api/openapi
    about: "Please join the #sig-moonwalk channel on our Slack!"
